# Generated by Django 3.2.6 on 2021-11-22 13:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App', '0003_remove_relationship_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Friend',
            new_name='Profile',
        ),
        migrations.AddField(
            model_name='relationship',
            name='status',
            field=models.CharField(choices=[('Send', 'Send'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default=1, max_length=15),
            preserve_default=False,
        ),
    ]
