# Generated by Django 3.2.6 on 2021-11-22 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_auto_20211122_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='status',
            field=models.CharField(choices=[('Send', 'Send'), ('Accepted', 'Accepted')], max_length=15),
        ),
    ]
