# Generated by Django 3.2.6 on 2021-11-22 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_alter_relationship_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relationship',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='relationship',
            name='sender',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='Relationship',
        ),
    ]
