# Generated by Django 3.2.6 on 2021-11-23 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_profile_relationship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='status',
            field=models.CharField(choices=[('send', 'send'), ('accepted', 'accepted')], max_length=10),
        ),
    ]
